### ISSUE TITLE
Blank screen after I try to edit custom map

### ISSUE THREAD

**Issue by ZeJayee** [Yulin-W/making-history-sandbox#39]
Using geojson, I made a map and when I try to colorize it, the screen just goes blank.
[Blank Screen.webm](https://user-images.githubusercontent.com/84470181/210783880-737ac94b-eb7c-42b3-85a4-2755e81d347f.webm)

**Comment by Yulin-W** [comment]
Thanks for bringing this up! I suspect the geojson had a different format to the one the app needs.

I made an update so that it should handle more geojson formats; hopefully that fixes the issue.

Try loading the geojson again and coloring. Let me know how it goes.

Side note: the update allows using top left LOAD button to load geojson and save using the geojson (though its fine to use the original side panel for loading too)

**Comment by ZeJayee** [comment]
It works! Off to editing I go!
Thanks for the quick response!
