### ISSUE TITLE
So, you say that there's plenty of GEOjsons online...

### ISSUE THREAD

**Issue by 4ngrythekidd** [Yulin-W/making-history-sandbox#46]
But, is there something that's even better than the default GEOjson that is in this sandbox? If so, where can I find a map with every single island, territory, state, province, region and what not? Where's the link?

**Comment by Yulin-W** [comment]
Sorry for the late reply. 

Files from "https://www.geoboundaries.org/" labelled as **ADM2 or larger** are better in terms of details than the default (the default file is basically a ADM1 level file for the world). Such files exist for individual countries and globally, albeit the global file is  very large and likely to cause significant lag or even crash, though the single country files should be fine.
- Note 1: **ADMx means x levels of administrative divisions** are present in the file (e.g. ADM0 is country, ADM1 is state/province, ADM2 is the next finer level, etc.)
- Note 2: Where possible, I recommend using the "**Simplified Files**" on the site and usually no more than ADM2 (since otherwise the file gets rather large and laggy)
- Note 3: Caveat: Region names aren't automatically loaded with these files (usually).

Also, some other miscellaineous geojson files:

US counties: https://gist.github.com/sdwfrost/d1c73f91dd9d175998ed166eb216994a
Countries (without further subdivisions): https://github.com/datasets/geo-countries/blob/master/data/countries.geojson
